Repository MayyarAA/studentplanner, pull requests merged in 2020-12, with the labels that each got.

#70 Integration of filter/sort feature into modals and card view
  filterList.php
  listView.php
Labels: Story 14, story 16

#71 Story 28: Infinite scrolling in lists
  ArchivedPage.php
  CSS/BoardView-Body.css
  listView.php
  selectBoard.php
Labels: Story 28

#68 Update README.md
  README.md
Labels: documentation

#74 Share boards with users taking the same course
  selectBoard.php
  shareBoardCourse.php
Labels: Story 36

#76 Story 26 - Delete and Archive Shortcuts
  listView.php
Labels: Story 26

#77 listview.php Empty Board Message
  listView.php
Labels: Story 35
