Repository MayyarAA/studentplanner, pull requests merged in 2020-10, with the labels that each got.

#11 Taskpage
  conn.php
  index.html
  taskDetails.html
  taskDetails.php
Labels: Story 30

#14 William's comment patch.
  login.php
  register.php
Labels: Story 33, Story 34

#12 List View for Tasks (Default List)
  listView.php
Labels: Story 32

#15 Added board view and delete task functionality
  boardView.html
  deleteTask.php
  jumbotron.css
Labels: Story 29, Story 31

#17 R2nasim log in ui: Created UI for log-in and Registration
  CSS/LogIn.css
  CSS/LoginCarousel.css
  CSS/Register.css
  Register.html
  conn.php
  imgs/Login-Key.jpg
  imgs/Profile-Icon.jpg
  index.html
  login.php
  register.php
Labels: Story 33, Story 34
