Repository MayyarAA/studentplanner, pull requests merged in 2020-11, with the labels that each got.

#24 Update ListView
  listView.php
Labels: Story 10

#29 Open Task View, View Details, Delete Task
  listView.php
  viewTask.php
Labels: Story 3

#32 Edit titles for existing lists
  listView.php
Labels: Story 12

#38 Assign task to a task list when creating task
  boardView.html
  listView.php
  taskDetails.html
  taskDetails.php
Labels: Story2

#39 Add Edit Task Functionality
  listView.php
  viewTask.php
Labels: Story 3

#41 Update query inputs for edit list, formatting and documentation
  listView.php
Labels: Story 12

#42 R2nasim ui/ux
  CSS/BoardView-Body.css
  CSS/BoardView.css
  CSS/LogIn.css
  index.html
  listView.php
  taskDetails.php
Labels: enhancement

#43 remove comment that stops query execution(deleting lists)
  listView.php
Labels: bug

#49 Story 24 - Board Sharing
  listView.php
  selectBoard.php
  taskDetails.php
  viewTask.php
Labels: Story 24

#50 Story 25 - Board access functionality
  listView.php
  login.php
  logout.php
  register.php
  selectBoard.php
  taskDetails.php
  viewTask.php
Labels: Story 25

#51 Archived Board
  ArchivedPage.php
  listView.php
  register.php
  selectBoard.php
Labels: Story 22

#59 Filtering tasks within Lists
  CSS/BoardView-Body.css
  filterList.php
  listView.php
Labels: Story 14

#54 added two deafult lists to-do and done
  selectBoard.php
Labels: Story 32

#57 Create Task Form Changes
  listView.php
Labels: Story 30, Story 4, Story2

#62 Added sort forms and queries onto filterList.php
  filterList.php
Labels: story 16

#63 Archive Task page functionality
  ArchivedPage.php
  deleteTask.php
  listView.php
  selectBoard.php
  viewTask.php
Labels: Story 22
